version: '3'

services:

  workspace:
    restart: always
    build:
      context: ./workspace
      args:
        - PUID=1000
        - PGID=1000
        - TZ=UTC
    volumes:
      - ../:/var/www
    env_file: env.dev
    tty: true

  php-fpm:
    restart: always
    build: ./php-fpm
    volumes:
      - ../:/var/www
    expose:
      - "9000"
    links:
      - workspace
    env_file: env.dev
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"

  nginx:
    restart: always
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes:
      - ../:/var/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  db:
    restart: always
    image: postgres:9.6
    volumes:
      - data:/var/lib/postgresql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file: env.dev

volumes:
  data:
